version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
    restart: unless-stopped
    # Add healthcheck for better orchestration
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  # backend:
  #   build: .
  #   ports:
  #     - "5000:5000"
  #   # ... other configurations
  #   # Ensure you have environment variables defined here or in an .env file
  #   # e.g., environment:
  #   #   - NODE_ENV=production
  #   #   - PORT=5000
  #   #   - MONGODB_URI=${MONGODB_URI}
  #   #   - JWT_SECRET_KEY=${JWT_SECRET_KEY}
  #   #   - REDIS_URL=${REDIS_URL}
