
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI} # This will come from your .env file
      - JWT_SECRET_KEY=${JWT_SECRET_KEY} # This will come from your .env file
      - FRONTEND_URL=${FRONTEND_URL} # This will come from your .env file
      - REDIS_URL=${REDIS_URL} # This will come from your .env file
      - PORT=5000 # Explicitly set PORT for the app
    restart: unless-stopped
    volumes:
      - ./logs:/usr/src/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api-docs"] # Ensure this endpoint exists and returns 2xx/3xx
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
